name: "Build Site"

on:
  schedule:
    - cron: '0 0 * * 0'
  
  workflow_dispatch:

jobs:
  CodeQL-Build-NodeJS:
    strategy:
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: javascript

    - run: |
       cd source/nodejs
       npm install
       npx lerna bootstrap
       npx lerna run build
       
       cd adaptivecards-site
       npm install rimraf --save
       npm install dts-generator --save
       npm install jest --save
       npx lerna run release
       npm run build

    # Deploy to gh-pages
    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: public
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

